### ISSUE TITLE
Add Mobile OS Comparison (Android vs iOS vs GrapheneOS) 

### ISSUE THREAD

**Issue by iAnonymous3000** [davidcollini/SoftwareCompare#3]
Add comparison table for mobile operating systems focusing on:
- Privacy features
- Security model
- Convenience/usability
- Ethics/transparency
etc.

Format similar to existing software comparisons, with verifiable sources for each checkmark.

### Todo
- [x] Create comparison criteria
- [x] Research current state
- [x] Add to site structure

This is simply a reminder for us to work together - in its current form, it's not thorough enough for implementation.
